version: '3.7'

services:
  api:
    image: patient_management_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      -  patient-app-network

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - patient-db-volume:/var/lib/postgresql/data
    networks:
      -  patient-app-network

volumes:
  patient-db-volume: {}

networks:
  patient-app-network: {}